import {StyleSheet} from 'react-native';

/** Mapped from `layouts/AppShell.css` + `components/AccountMenu.css` (mobile). */
export const HEADER = {
  text: '#1A202C',
  textSecondary: '#718096',
  primary: '#3182CE',
  primaryDark: '#2C5282',
  border: '#E2E8F0',
  card: '#FFFFFF',
  error: '#E53E3E',
  avatarBg: 'rgba(49, 130, 206, 0.18)',
  hover: 'rgba(49, 130, 206, 0.08)',
} as const;

export const accountMenuStyles = StyleSheet.create({
  triggerWrap: {
    minWidth: 48,
    minHeight: 44,
    justifyContent: 'center',
    overflow: 'visible',
  },
  triggerWrapCompact: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  trigger: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 40,
    paddingVertical: 2,
    paddingLeft: 2,
    paddingRight: 2,
    borderRadius: 999,
    gap: 2,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: HEADER.avatarBg,
  },
  avatarText: {
    color: HEADER.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 28, 46, 0.18)',
  },
  panelWrap: {
    position: 'absolute',
    right: 12,
    minWidth: 220,
    maxWidth: 320,
  },
  panel: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: HEADER.border,
    backgroundColor: HEADER.card,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 8,
    maxHeight: 420,
  },
  identity: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: HEADER.border,
    marginBottom: 4,
    gap: 2,
  },
  identityName: {
    fontSize: 14,
    fontWeight: '700',
    color: HEADER.text,
  },
  identityPhone: {
    fontSize: 12,
    color: HEADER.textSecondary,
  },
  modeCurrent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginBottom: 4,
  },
  modeBlock: {
    paddingVertical: 4,
    paddingBottom: 8,
    marginBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: HEADER.border,
  },
  modeCurrentText: {
    fontSize: 13,
    fontWeight: '700',
    color: HEADER.primaryDark,
  },
  modeUnavailable: {
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    paddingBottom: 4,
  },
  modeUnavailableTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: HEADER.textSecondary,
  },
  modeCreate: {
    alignSelf: 'stretch',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: `${HEADER.primary}59`,
    borderRadius: 10,
    backgroundColor: `${HEADER.primary}14`,
    alignItems: 'center',
  },
  modeCreateText: {
    fontSize: 13,
    fontWeight: '600',
    color: HEADER.primaryDark,
  },
  item: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  itemLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: HEADER.text,
  },
  itemHint: {
    fontSize: 12,
    fontWeight: '400',
    color: HEADER.textSecondary,
    marginTop: 2,
  },
  itemDanger: {
    color: HEADER.error,
  },
  themes: {
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 10,
    marginBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: HEADER.border,
  },
  themesLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  themesSwatches: {
    flexDirection: 'row',
    gap: 6,
  },
  themeSwatch: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  themeDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  themeName: {
    fontSize: 11,
    fontWeight: '600',
    color: HEADER.textSecondary,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 4,
    overflow: 'visible',
  },
  toggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  toggleLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
});
